#!/bin/sh

xinitrc=$HOME/.xinitrc

if [ -f $xinitrc ]; then
    $xinitrc
fi

for file in $HOME/.config/environment.d/*.conf; do
    if [ -f "$file" ]; then
	set -a
	. "$file"
	set +a
    fi
done

if command -v picom >/dev/null 2>&1; then
    pkill picom && picom -b
else
    echo "Picom is not installed."
fi

exec dwm
